### ISSUE TITLE
Tlmgr returning error in Linux

### ISSUE THREAD

**Issue by naveen521kk** [yihui/tinytex-releases#1]
I downloaded https://github.com/yihui/tinytex-releases/releases/download/v2020.09/TinyTeX-1.tar.gz in Linux.
I extracted it using the below command
```sh
tar -xvzf "TinyTeX-1.tar.gz" 
```
At first, I could find my extracted folder. Later I found it was `.TinyTeX`(Hidden). Then I wanted to create symlinks to start using it. So I typed the below command
```sh
cd .TinyTeX && bin/x86_64-linux/tlmgr path add
```
Then it returned a weird error.
```
Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) (@INC contains: //texmf-dist/scripts/texlive //tlpkg /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at bin/x86_64-linux/tlmgr line 101.
BEGIN failed--compilation aborted at bin/x86_64-linux/tlmgr line 101.
```
Looks like the way it was build was the issue. I think @yihui . Could you try and verify whether this works?

Here, I attached a Google Colab copy of what happened. 
https://gist.github.com/naveen521kk/3fe9f54a4e82efef97903a272380e541
Note: Their all bash command should start with `!`.

**Comment by yihui** [comment]
You need to `cd` into the directory of `tlmgr`:
https://github.com/yihui/tinytex/blob/9ba0e4eef2ea98b8a3cef4eff65bd91c51c7e4ab/tools/install-bin-unix.sh#L16-L18

It seems that `tlmgr` under `~/.TinyTeX/bin/x86_64-linux` is dependent on the working directory.

**Comment by naveen521kk** [comment]
I appreciate a clear mention of this in docs. I haven't tried it yet. Once, I tried it and confirm I will close this issue.

**Comment by yihui** [comment]
To be honest, this is the first time I have discovered it over the several years of using `tlmgr`. Perhaps I'd never know it by myself, and was just too lucky to have done `tlmgr path add` correctly in the first time :)

**Comment by naveen521kk** [comment]
Yes, what you said worked. I tried the below command and it worked without any errors. 
```sh
cd .TinyTeX/bin/x86_64-linux && ./tlmgr path add
```

**Comment by yihui** [comment]
If you want to install TinyTeX on Linux, you can use the method here: https://yihui.org/tinytex/#installation which essentially runs this script: https://github.com/yihui/tinytex/blob/master/tools/install-bin-unix.sh

**Comment by naveen521kk** [comment]
I am closing this as this is fixed. Also, why not publish to `apt` for TexLive?

**Comment by yihui** [comment]
That might be a good idea, but I'm not interested in it. Users have too little freedom with a Debian package (which may make sense for other packages but not for TeX Live in my opinion): https://yihui.org/tinytex/pain/

If I were to make this a package at all, I'd probably consider Homebrew instead (which works for both macOS and Linux), so users can `brew install tinytex`. I have done some work a couple of years ago: https://github.com/yihui/homebrew-tinytex I didn't think it was a good idea at that time, but I think it's okay now because we have got stable releases.
