### ISSUE TITLE
Problem installing in MacOS

### ISSUE THREAD

**Issue by drfurtado** [yihui/tinytex-releases#11]
I am trying to install it but I am getting the following error:

```
> install.packages("~/Downloads/TinyTeX-1-v2021.02.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into ‘/Users/ofurtado/Library/R/4.0/library’
(as ‘lib’ is unspecified)
Error in install.packages : file ‘~/Downloads/TinyTeX-1-v2021.02.tgz’ is not a macOS binary package
```
I am using:
MacOS Catalina: 10.15.7
Latest version of R
Latest version of Rstudio

Any help would be greatly appreciated.

**Comment by cderv** [comment]
Hi @drfurtado, 

I don't think you are trying the correct command. `TinyTeX-1-v2021.02.tgz` is not a R package. 
Please follow the README here https://github.com/yihui/tinytex-releases#r

See also https://yihui.org/tinytex/#installation

Is this helpful ?
