### ISSUE TITLE
Build a binary for TeX Live 2021

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex-releases#12]
It was released yesterday 01/04/2021.

As it is not possible to update between version of TeXLive, **tinytex** users are stuck with frozen repo. No install possible

Will fix https://github.com/yihui/tinytex/issues/293

**Comment by nealkruis** [comment]
I have a CI that installs TinyTex through [this GitHub action](https://github.com/r-lib/actions/tree/master/setup-tinytex) and then uses tlmgr to install packages. I believe this issue is now causing all my builds to fail.

@cderv, @yihui, do you plan to do a manual build for TeX Live 2021? What do you think the timeline is for getting something deployed?

**Comment by yihui** [comment]
I've been working on it today. If you trigger a rebuild of the action, it should download the 2021 version now.

**Comment by nealkruis** [comment]
Indeed! Thanks!

**Comment by abel-betraoui** [comment]
I believe I'm encountering the same issue as nealkruis was last year. There was a texLive release on the 3rd of April 2022 which is raising the following error during the installation process:

```
../install-tl-20211227/install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2021
 repository: 2022
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
 ```
 
@cderv  @yihui  Will you do a manual build for TeX Live 2022 ?

**Comment by cderv** [comment]
Hi @abel-betraoui, 

We did trigger the rebuild already. The daily release will be up to date, and you have also a specific 2022.04.04 release in addition to the usual monthly release 2022.04. See https://github.com/yihui/tinytex-releases/releases

Using `tinytex::install_tinytex()` or `tinytex::reinstall_tinytex()` should install the daily version by default and you should be good to go.  

I'll close this issue from last year now, and we'll probably open one next year 😅 

Related discussion from this year also in a past year thread : https://github.com/yihui/tinytex/issues/293
