### ISSUE TITLE
Links to download TinyTeX zip files for Windows seem broken

### ISSUE THREAD

**Issue by ClinBAY** [yihui/tinytex-releases#17]
The links to download the TinyTeX-0.zip, TinyTex-1.zip and TinyText.zip files for Windows from the page https://github.com/yihui/tinytex-releases seem broken. 

It results in an error:
 {"message":"Artifact not found or access denied."}

The batch file for Windows generates the same error.

**Comment by yihui** [comment]
Should be fixed now. Thanks a lot for the report!
