### ISSUE TITLE
Keep old releases

### ISSUE THREAD

**Issue by krlmlr** [yihui/tinytex-releases#19]
Some of my documents rely on the outdated/obsolete/broken/unmaintained/wonderful `{tabu}` package which finally breaks in TeXlive 2021. Can we please keep old versions around for some time to account for this and similar situations?

**Comment by yihui** [comment]
I won't purge old releases by myself, and I don't think Github will purge them, either.

**Comment by cderv** [comment]
Great ! 

I think we're good then. @krlmlr we could close this I guess ? 
Or was there another point to look into ?

**Comment by krlmlr** [comment]
Thanks, updated the blog post.

**Comment by cderv** [comment]
Thanks! 

Can you just update my name at the end to correct the typo ? 

> Thanks Christophe Devrieux for the hint!

````diff
-Devrieux 
+Dervieux
````

Thank you !

**Comment by fkohrt** [comment]
@cderv `tinytex::tlmgr_repo(url = ...)`, in contrast to `tinytex::tlmgr("option repository ...)`, does not work with historic Tex Live releases, because `/systems/texlive/tlnet` gets automatically appended to the `url`, e.g. `https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2020/tlnet-final` → `https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2020/tlnet-final/systems/texlive/tlnet`

The same is true for the `repository` passed as argument to `tinytex::install_tinytex`.

**Comment by cderv** [comment]
Good to know ! This seems like something to fix and append only if not already in the url.

**Comment by cderv** [comment]
For now, this would mean to use 
````
tinytex::tlmgr_repo(url = I("https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2020/tlnet-final"))
````
and same in 
``
tinytex::install_tinytex(repository = I("https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2020/tlnet-final"))`
````

But you need to know that the url won't work otherwise. 

We could detect by testing the url after append and use the original one if not accessible.

**Comment by krlmlr** [comment]
...and fixed for now in https://www.cynkra.com/blog/2021-10-07-old-texlive/. Thanks for the feedback!

**Comment by cderv** [comment]
FYI we have added a tweak in `normalize_repo()` to not append if the url + append is not reachable (to status 200 request). This requires `capabilities('libcurl')` but can solve case like this when they arises.

So now it should work fine with `https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2020/tlnet-final` too.
