### ISSUE TITLE
管理员权限命令行执行tlmgr时报错

### ISSUE THREAD

**Issue by lon91ong** [yihui/tinytex-releases#21]
使用最新的（2022-01）版本，管理员权限执行tlmgr命令时报错：
```
Could not determine directory of tlmgr executable, maybe shared library woes?
Check for error messages above at E:\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 72.
BEGIN failed--compilation aborted at E:\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 81.
```
同样的目录配置, 使用去年的(2021.02版)时正常

使用`tl-tray-menu.exe`打开的命令行窗口执行tlmgr没有报错, 但是命令似乎没有生效, `tlmgr update --list`结果如下:
> tlmgr.pl: package repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
> tlmgr.pl: no updates available

**Comment by lon91ong** [comment]
多番尝试, 找到解决办法了, 定义环境变量`set TEXMFROOT=TinyTeX Path`即可

**Comment by bluestyle97** [comment]
You save my day!
