### ISSUE TITLE
Should we make tinytex R package compatible with those packages ?  

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex-releases#4]
I found that there are some incompatibilities with R package functions. 

For example, see https://github.com/cderv/r-bucket/issues/3

* `tinytex_root()` won't work with either choco and scoop due to the way their shims are working. 

All functions that use this `tinytex_root()` won't work. 

@yihui Should we make them compatible ? Either by changing the packages, or tweaking **tinytex** ? 

I am not sure are they are mainly for use with installation from **tinytex** R package itself but that seems to be disturbing for users that they don't work. And it seems easy to detect scoop or choco because we know where they install things.

**Comment by yihui** [comment]
Yes, we should. I'll fix `tinytex_root()` after I know more info about scoop. Thanks!

**Comment by cderv** [comment]
As I am work on windows, I can try to solve it if you want. I know less about tinytex but I can test easily. Anyway, ping me for any information.
