### ISSUE TITLE
install failed in Windows 10

### ISSUE THREAD

**Issue by lon91ong** [yihui/tinytex-releases#9]
Flowing the discription over [here](https://yihui.org/tinytex/#installation)
After download the install.zip, extract to %appdata% path
then run `install-tl-windows.bat` and get error info:
```bash
C:/Users/Administrator/AppData/Roaming/TinyTeX>.\install-tl-windows
Loading C:/Users/Administrator/AppData/Roaming/TinyTeX/tlpkg/texlive.tlpdb
Aborting, cannot find either scheme-full or scheme-minimal at C:\Users\Administrator\AppData\Roaming\TinyTeX\install-tl line 1797.
```
HELP!

**Comment by yihui** [comment]
The description at https://yihui.org/tinytex/#installation didn't mention `install-tl-windows.bat`. Where did you get that?

The instructions on that page told you to use `install-bin-windows.bat`. Did you try that?

**Comment by lon91ong** [comment]
It's in the zip file https://yihui.org/tinytex/TinyTeX.zip

[install-bin-windows.bat](https://github.com/yihui/tinytex/blob/master/tools/install-bin-windows.bat) only download and unzip

Is TinyTex portable?

**Comment by yihui** [comment]
> It's in the zip file https://yihui.org/tinytex/TinyTeX.zip

The installation instruction didn't tell you to run it.

> [install-bin-windows.bat](https://github.com/yihui/tinytex/blob/master/tools/install-bin-windows.bat) only download and unzip

That's not completely true. After unzipping, it moves the folder to `%APPDATA%`: https://github.com/yihui/tinytex/blob/ce0e9d311830673dbfd2aa945145c54c45020b7f/tools/install-bin-windows.bat#L24

I just realized that I forgot to run `tlmgr path add`, and just did it. Please download `install-bin-windows.bat` again and run it.

> Is TinyTex portable?

Yes, I'd appreciate it if you could spend one more minute on reading the title and subtitle of the homepage: https://yihui.org/tinytex/

**Comment by yihui** [comment]
I have also deleted `install-bin-windows.bat` from the latest zip package.
